/* Carica stile e inserisce Dimensionamento Opere prima dello Stato Analisi Economica */
(function initDimensionamentoMarkup(){
  if(!document.querySelector('link[href*="dimensionamento-v1.css"]')){
    const link=document.createElement('link');link.rel='stylesheet';link.href='dimensionamento-v1.css?v=1';document.head.appendChild(link);
  }
  const analysis=document.querySelector('#tab-analisi .analysis');
  if(analysis&&!document.querySelector('.dimensioning')){
    analysis.insertAdjacentHTML('beforebegin',`
      <section class="accordion dimensioning open">
        <button class="section-head" type="button"><span>▦&nbsp;&nbsp;Dimensionamento Opere</span><span class="chevron">⌄</span></button>
        <div class="section-body dimensioning-body">
          <div class="dim-table">
            <div class="dim-row dim-head">
              <div>DESCRIZIONE / ELEMENTO</div><div>MQ</div><div>IMP. MECCANICI<br>€/MQ</div><div>IMP. ELETTRICI<br>€/MQ</div><div>TOT. MECCANICI</div><div>TOT. ELETTRICI</div><div>TOTALE RIGA</div><div></div>
            </div>
            <div id="dimRows"></div>
            <div class="dim-row dim-total-row">
              <div class="dim-total-label">TOTALI</div>
              <div class="dim-read"><span id="dimMqTotal">0,00</span></div>
              <div></div><div></div>
              <div class="dim-read"><span id="dimMechGrand">0,00</span>&nbsp;€</div>
              <div class="dim-read elec"><span id="dimElecGrand">0,00</span>&nbsp;€</div>
              <div class="dim-read total"><span id="dimCalcGrand">0,00</span>&nbsp;€</div><div></div>
            </div>
          </div>
          <div class="dim-actions"><button id="dimAdd" class="dim-add" type="button">＋ Aggiungi elemento</button></div>

          <div class="dim-summary">
            <div class="dim-box"><div class="dim-box-label">Totale calcolato</div><div class="dim-box-value"><span id="dimCalcBox">0,00</span> €</div></div>
            <div class="dim-box rounded"><div class="dim-box-label">Totale opere arrotondato</div><div class="dim-round-line"><input id="dimRounded" class="dim-round-input" value="0,00" inputmode="decimal"><button id="dimRoundedReset" class="dim-reset" type="button" title="Ripristina totale calcolato">↺</button></div></div>
            <div class="dim-box"><div class="dim-box-label">Compenso complessivo</div><div class="dim-slider-line"><input id="dimFeePct" type="range" min="0" max="15" step="0.1" value="7"><span id="dimFeePctLabel" class="dim-slider-value">7,0%</span></div></div>
            <div class="dim-box"><div class="dim-box-label">Fattore complessità IE</div><div class="dim-factor-line"><input id="dimIeFactor" class="dim-factor-input" value="1,00" inputmode="decimal"><span class="dim-factor-note">applicato alla quota elettrica di ogni fase</span></div></div>
          </div>

          <div class="phase-strip">
            <div class="phase-caption"><strong>RIPARTIZIONE FASI</strong><span>modificabile · totale 100%</span></div>
            <div class="phase-card"><div class="phase-card-head"><span class="phase-name">PP · Preliminare</span><span class="phase-pct-wrap"><input class="phase-pct" value="10" type="number" min="0" max="100" step="1"><span>%</span></span></div><div class="phase-effective">aliquota <span class="phase-effective-value">0,70%</span></div><div class="phase-result"><span class="phase-result-value">0,00</span> €</div></div>
            <div class="phase-card"><div class="phase-card-head"><span class="phase-name">PD · Definitiva</span><span class="phase-pct-wrap"><input class="phase-pct" value="35" type="number" min="0" max="100" step="1"><span>%</span></span></div><div class="phase-effective">aliquota <span class="phase-effective-value">2,45%</span></div><div class="phase-result"><span class="phase-result-value">0,00</span> €</div></div>
            <div class="phase-card"><div class="phase-card-head"><span class="phase-name">PE · Esecutiva</span><span class="phase-pct-wrap"><input class="phase-pct" value="25" type="number" min="0" max="100" step="1"><span>%</span></span></div><div class="phase-effective">aliquota <span class="phase-effective-value">1,75%</span></div><div class="phase-result"><span class="phase-result-value">0,00</span> €</div></div>
            <div class="phase-card"><div class="phase-card-head"><span class="phase-name">DL · Direzione lavori</span><span class="phase-pct-wrap"><input class="phase-pct" value="30" type="number" min="0" max="100" step="1"><span>%</span></span></div><div class="phase-effective">aliquota <span class="phase-effective-value">2,10%</span></div><div class="phase-result"><span class="phase-result-value">0,00</span> €</div></div>
            <div id="phaseTotalCheck" class="phase-total-check"><span>TOTALE</span><strong id="phaseTotalPct">100%</strong></div>
          </div>

          <div class="dim-transfer-row"><span class="dim-transfer-note">Proposta indicativa: <strong><span id="dimProposalTotal">0,00</span> €</strong> · dopo il trasferimento i valori sotto restano modificabili</span><span id="dimFlash" class="dim-flash">✓ Trasferito</span><button id="dimTransfer" class="dim-transfer" type="button">↓ Usa come proposta economica</button></div>
        </div>
      </section>`);
  }
})();

document.querySelectorAll('.section-head').forEach(btn=>{btn.addEventListener('click',()=>btn.closest('.accordion').classList.toggle('open'))});
document.querySelectorAll('.tab').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('tab-'+btn.dataset.tab)?.classList.add('active');history.replaceState(null,'','#'+btn.dataset.tab)})});
const star=document.getElementById('star');star?.addEventListener('click',()=>{star.classList.toggle('active');star.setAttribute('aria-pressed',star.classList.contains('active')?'true':'false')});
function parseItalianNumber(v){return Number(String(v??'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
function formatItalianNumber(n){return Number(n||0).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2})}
function formatPct(n,digits=2){return Number(n||0).toLocaleString('it-IT',{minimumFractionDigits:digits,maximumFractionDigits:digits})+'%'}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value}

const money=[...document.querySelectorAll('.money')],total=document.getElementById('totaleOfferta');
function recalcOffer(){const sum=money.reduce((s,i)=>s+parseItalianNumber(i.value),0);if(total)total.value=formatItalianNumber(sum)}
money.forEach(input=>{input.addEventListener('focus',()=>input.select());input.addEventListener('blur',()=>{input.value=formatItalianNumber(parseItalianNumber(input.value));recalcOffer()});input.addEventListener('input',recalcOffer)});

const aeProposal=[...document.querySelectorAll('.ae-proposal')],aeCosts=[...document.querySelectorAll('.ae-cost')],aeTradeValues=[...document.querySelectorAll('.ae-discount')],tradePct=document.getElementById('tradePct'),tradePctLabel=document.getElementById('tradePctLabel');
function recalcEconomic(){const pct=Number(tradePct?.value||0);if(tradePctLabel)tradePctLabel.textContent=pct+'%';let gross=0,costs=0;aeProposal.forEach((input,index)=>{const phaseValue=parseItalianNumber(input.value);gross+=phaseValue;const afterTrade=phaseValue*(1-pct/100);if(aeTradeValues[index])aeTradeValues[index].textContent=formatItalianNumber(afterTrade)});aeCosts.forEach(input=>costs+=parseItalianNumber(input.value));const netRevenue=gross*(1-pct/100),generalExpenses=0,mol=netRevenue-costs,mon=mol-generalExpenses,molPct=netRevenue!==0?mol/netRevenue*100:0,profitPct=netRevenue!==0?mon/netRevenue*100:0;setText('aeGross',formatItalianNumber(gross));setText('aeDiscountTotal',formatItalianNumber(netRevenue));setText('aeCosts',formatItalianNumber(costs));setText('aeMol',formatItalianNumber(mol));setText('aeMolPct',formatPct(molPct));setText('aeGeneralExpenses',formatItalianNumber(generalExpenses));setText('aeMon',formatItalianNumber(mon));setText('aeProfitPct',formatPct(profitPct))}
[...aeProposal,...aeCosts].forEach(input=>{input.addEventListener('focus',()=>input.select());input.addEventListener('input',recalcEconomic);input.addEventListener('blur',()=>{input.value=formatItalianNumber(parseItalianNumber(input.value));recalcEconomic()})});tradePct?.addEventListener('input',recalcEconomic);recalcEconomic();

const dimRows=document.getElementById('dimRows'),dimAdd=document.getElementById('dimAdd'),dimRounded=document.getElementById('dimRounded'),dimRoundedReset=document.getElementById('dimRoundedReset'),dimFeePct=document.getElementById('dimFeePct'),dimFeePctLabel=document.getElementById('dimFeePctLabel'),dimIeFactor=document.getElementById('dimIeFactor'),dimTransfer=document.getElementById('dimTransfer'),dimFlash=document.getElementById('dimFlash'),phasePctInputs=[...document.querySelectorAll('.phase-pct')];
let dimRoundedManual=false,phaseValues=[0,0,0,0];
function dimRowTemplate(){return `<div class="dim-row dim-data"><div><input class="dim-desc" type="text" placeholder="Descrizione / elemento"></div><div><input class="dim-mq" type="text" inputmode="decimal" value="0,00"></div><div><input class="dim-mech-rate" type="text" inputmode="decimal" value="0,00"></div><div><input class="dim-elec-rate" type="text" inputmode="decimal" value="0,00"></div><div class="dim-read"><span class="dim-mech-total">0,00</span>&nbsp;€</div><div class="dim-read elec"><span class="dim-elec-total">0,00</span>&nbsp;€</div><div class="dim-read total"><span class="dim-row-total">0,00</span>&nbsp;€</div><div><button class="dim-delete" type="button" title="Elimina riga">×</button></div></div>`}
function bindDimRow(row){row.querySelector('.dim-delete')?.addEventListener('click',()=>{row.remove();recalcDimensioning()});[...row.querySelectorAll('.dim-mq,.dim-mech-rate,.dim-elec-rate')].forEach(input=>{input.addEventListener('focus',()=>input.select());input.addEventListener('input',recalcDimensioning);input.addEventListener('blur',()=>{input.value=formatItalianNumber(parseItalianNumber(input.value));recalcDimensioning()})})}
function addDimRow(){if(!dimRows)return;dimRows.insertAdjacentHTML('beforeend',dimRowTemplate());bindDimRow(dimRows.lastElementChild);recalcDimensioning()}
dimAdd?.addEventListener('click',addDimRow);dimRounded?.addEventListener('focus',()=>dimRounded.select());dimRounded?.addEventListener('input',()=>{dimRoundedManual=true;recalcDimensioning()});dimRounded?.addEventListener('blur',()=>{dimRounded.value=formatItalianNumber(parseItalianNumber(dimRounded.value));recalcDimensioning()});dimRoundedReset?.addEventListener('click',()=>{dimRoundedManual=false;recalcDimensioning()});dimFeePct?.addEventListener('input',recalcDimensioning);dimIeFactor?.addEventListener('input',recalcDimensioning);dimIeFactor?.addEventListener('blur',()=>{dimIeFactor.value=Number(parseItalianNumber(dimIeFactor.value)||1).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2});recalcDimensioning()});phasePctInputs.forEach(i=>i.addEventListener('input',recalcDimensioning));
function recalcDimensioning(){if(!dimRows)return;let mqTotal=0,mechTotal=0,elecTotal=0;[...dimRows.querySelectorAll('.dim-data')].forEach(row=>{const mq=parseItalianNumber(row.querySelector('.dim-mq')?.value),mechRate=parseItalianNumber(row.querySelector('.dim-mech-rate')?.value),elecRate=parseItalianNumber(row.querySelector('.dim-elec-rate')?.value),mech=mq*mechRate,elec=mq*elecRate,rowTotal=mech+elec;mqTotal+=mq;mechTotal+=mech;elecTotal+=elec;row.querySelector('.dim-mech-total').textContent=formatItalianNumber(mech);row.querySelector('.dim-elec-total').textContent=formatItalianNumber(elec);row.querySelector('.dim-row-total').textContent=formatItalianNumber(rowTotal)});const calcTotal=mechTotal+elecTotal;setText('dimMqTotal',formatItalianNumber(mqTotal));setText('dimMechGrand',formatItalianNumber(mechTotal));setText('dimElecGrand',formatItalianNumber(elecTotal));setText('dimCalcGrand',formatItalianNumber(calcTotal));setText('dimCalcBox',formatItalianNumber(calcTotal));if(dimRounded&&!dimRoundedManual)dimRounded.value=formatItalianNumber(calcTotal);const rounded=dimRounded?parseItalianNumber(dimRounded.value):calcTotal,scale=calcTotal>0?rounded/calcTotal:1,mechRounded=mechTotal*scale,elecRounded=elecTotal*scale,feePct=Number(dimFeePct?.value||7);if(dimFeePctLabel)dimFeePctLabel.textContent=Number(feePct).toLocaleString('it-IT',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';const ieFactor=Math.max(0,parseItalianNumber(dimIeFactor?.value)||1),shares=phasePctInputs.map(i=>Number(i.value||0)),shareTotal=shares.reduce((a,b)=>a+b,0),check=document.getElementById('phaseTotalCheck');setText('phaseTotalPct',Number(shareTotal).toLocaleString('it-IT',{maximumFractionDigits:1})+'%');check?.classList.toggle('invalid',Math.abs(shareTotal-100)>0.01);const phaseResultEls=[...document.querySelectorAll('.phase-result-value')],phaseEffEls=[...document.querySelectorAll('.phase-effective-value')];phaseValues=shares.map((share,index)=>{const effectivePct=feePct*share/100;if(phaseEffEls[index])phaseEffEls[index].textContent=Number(effectivePct).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';const mechFee=mechRounded*effectivePct/100,elecFee=elecRounded*effectivePct/100*ieFactor,phaseTotal=mechFee+elecFee;if(phaseResultEls[index])phaseResultEls[index].textContent=formatItalianNumber(phaseTotal);return phaseTotal});setText('dimProposalTotal',formatItalianNumber(phaseValues.reduce((a,b)=>a+b,0)));if(dimTransfer)dimTransfer.disabled=Math.abs(shareTotal-100)>0.01}
dimTransfer?.addEventListener('click',()=>{[...document.querySelectorAll('.ae-proposal')].slice(0,4).forEach((input,index)=>input.value=formatItalianNumber(phaseValues[index]||0));recalcEconomic();if(dimFlash){dimFlash.classList.add('show');setTimeout(()=>dimFlash.classList.remove('show'),1600)}});if(dimRows){for(let i=0;i<3;i++)addDimRow();recalcDimensioning()}

function initColumnResizers(){const table=document.querySelector('.economic-table'),headCells=[...document.querySelectorAll('.economic-head>div')],handles=[...document.querySelectorAll('.col-resizer')];if(!table||headCells.length<4||!handles.length)return;const mins=[150,85,105,110];let widths=null;function captureWidths(){widths=headCells.slice(0,4).map(c=>c.getBoundingClientRect().width);widths.forEach((w,i)=>table.style.setProperty(`--ae-col${i+1}`,`${w}px`))}handles.forEach(handle=>{handle.addEventListener('pointerdown',e=>{e.preventDefault();if(!widths)captureWidths();const index=Number(handle.dataset.col)-1,startX=e.clientX,startA=widths[index],startB=widths[index+1];handle.classList.add('dragging');handle.setPointerCapture?.(e.pointerId);const move=ev=>{let delta=ev.clientX-startX;delta=Math.max(mins[index]-startA,Math.min(startB-mins[index+1],delta));widths[index]=startA+delta;widths[index+1]=startB-delta;table.style.setProperty(`--ae-col${index+1}`,`${widths[index]}px`);table.style.setProperty(`--ae-col${index+2}`,`${widths[index+1]}px`)};const up=ev=>{handle.classList.remove('dragging');handle.releasePointerCapture?.(ev.pointerId);handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up);handle.removeEventListener('pointercancel',up)};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up);handle.addEventListener('pointercancel',up)});handle.addEventListener('dblclick',()=>{widths=null;for(let i=1;i<=4;i++)table.style.removeProperty(`--ae-col${i}`)})})}initColumnResizers();
function openHashTab(){const wanted=(location.hash||'').replace('#','');if(!wanted)return;const btn=document.querySelector(`.tab[data-tab="${wanted}"]`);if(btn)btn.click()}openHashTab();